### ISSUE TITLE
La méthode getReservations n'affiche pas les réunions privées dans ses lieux

### ISSUE THREAD

**Issue by alexis-allemann** [alexis-allemann/PRO-B01#82]
Dans le calendrier de l'hôte, il doit pouvoir avoir un aperçu sur les réservations dans ses lieux. Ca marche bien mais les réunions privées ne sont pas affichées 😢

**Comment by Kyoden28** [comment]
A retester sur Heroku Dev, petite modification mineur en rapport avec l'issue 88 (erreur champ isPrivate) car normalement il y a pas de filtre sur la privacité

**Comment by alexis-allemann** [comment]
Testé sur DEV avec front-end : c'est OK
