### ISSUE TITLE
Générer build pour IOS

### ISSUE THREAD

**Issue by alexis-allemann** [alexis-allemann/PRO-B01#83]
Prendre la version qui est master et faire un build IOS. Tester les fonctionnalités.

**Comment by alex-mottier** [comment]
Il faut avoir un mac pour pouvoir générer le build. Il faut avoir les certificats pour pouvoir lier Expo avec le compte Apple Developper...

**Comment by alex-mottier** [comment]
Besoin d'un mac pour le faire
