### ISSUE TITLE
Erreur champ isPrivate lors d'une MAJ

### ISSUE THREAD

**Issue by alexis-allemann** [alexis-allemann/PRO-B01#88]
Dans les meetings, lors d'une mise à jour, le champ "isPrivate" n'est pas mis à jour selon les nouvelles données envoyées.

**Comment by Kyoden28** [comment]
Modifié sur fb-fix-issues, en attente de test sur Heroku Dev

**Comment by alexis-allemann** [comment]
Pas ok...

**Comment by Kyoden28** [comment]
Retester et good chez nous. A valider

**Comment by alexis-allemann** [comment]
Tout bon 👍🏼
