### ISSUE TITLE
Si un hébergeur supprimer un lieu, cela supprime en cascade les meetings dans le lieu

### ISSUE THREAD

**Issue by alexis-allemann** [alexis-allemann/PRO-B01#93]
Permet d'éviter des incohérances

**Comment by Kyoden28** [comment]
A discuter en groupe (Vu avec @Alois @hakimbalestrieri hier) . Peut-être partir sur une idée de rendre inactif le lieu, au lieu de le delete les informations

**Comment by alexis-allemann** [comment]
Oui effectivement c'est mieux 👍🏼

**Comment by AloisChristen** [comment]
cleared by #118
