### ISSUE TITLE
Méthode getCreatedMeetings renvoie tjr un seul participant

### ISSUE THREAD

**Issue by alexis-allemann** [alexis-allemann/PRO-B01#94]
La méthode renvoie toujours un tableau avec comme seul participant le owner. Pourtant d'autre étudiants sont inscrits dans le meeting et donc l'affichage du nombre de participants est faux.

**Comment by Kyoden28** [comment]
![image](https://user-images.githubusercontent.com/35340658/119049940-794f5100-b9c1-11eb-813f-c74baa27b434.png)

Testé et renvoie bien deux utilisateurs au niveau de members-id. A nécessiter un reset de l'application @alexis-allemann

**Comment by Kyoden28** [comment]
(Ou un swipe down pour refresh) 
mais sinon méthode okay de notre côté. A valider et close

**Comment by alexis-allemann** [comment]
Okey tout bon
