### ISSUE TITLE
Bug dans l'agenda avec les meetings

### ISSUE THREAD

**Issue by alex-mottier** [alexis-allemann/PRO-B01#97]
Le point de la réunion n'apparait que si le jour est sélectionné:
![image](https://user-images.githubusercontent.com/43849134/119033821-fa045200-b9ad-11eb-856e-cf997102f8cc.png)
Si c'est un autre jour le meeting n'apparait pas : 
![image](https://user-images.githubusercontent.com/43849134/119033846-025c8d00-b9ae-11eb-871f-c93fc1e23e1f.png)

**Comment by alexis-allemann** [comment]
Ca devrait être bon là 👍🏼
